apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-instance
  namespace: digitalmoney
  labels:
    name: prometheus-instance
    app: prometheus-app
    project: digitalmoney
spec:
  replicas: 2
  serviceAccountName: prometheus-k8s
  securityContext: {}
  serviceMonitorSelector: 
    matchLabels:
      name: prometheus-service-monitor
    ruleSelector: {}