apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-instance-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ocs-storagecluster-cephfs
