apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: besu-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: azurefile-csi-nfs
  volumeMode: Filesystem