kind: ConfigMap
apiVersion: v1
metadata:
  name: besu-config-toml
immutable: false
data:
  config.toml: |-
    # Valid TOML config file

    # P2P network
    #p2p-enabled=
    #discovery-enabled=
    #p2p-host=
    #p2p-port=
    #max-peers=

    data-path="/opt/data"
    logging="INFO"
    #genesisFilePath="/etc/genesis/genesis.json"
    
    # Transaction Pool
    tx-pool-retention-hours="999"
    tx-pool-max-size="1024"

    # # Network
    # bootnodes=["enode://001@123:4567", "enode://002@123:4567", "enode://003@123:4567"]

    # # Chain
    # genesis-file="~/genesis.json" # Path to the custom genesis file
    # # Mining
    # miner-enabled=true
    # miner-coinbase="0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"


    # host-whitelist=

    # # JSON-RPC
    # rpc-http-enabled=
    # rpc-http-host=
    # rpc-http-port=
    # rpc-http-api=
    # rpc-http-cors-origins=
    # rpc-http-authentication-enabled=

    # # GRAPHQL-RPC
    # graphql-http-enabled=
    # graphql-http-host=
    # graphql-http-port=
    # graphql-http-cors-origins=

    # # WebSockets API
    # rpc-ws-enabled=
    # rpc-ws-host=
    # rpc-ws-port=
    # rpc-ws-api=
    # #rpc-ws-apis=["DEBUG","ETH"]
    # rpc-ws-authentication-enabled=

    # # Permissioning
    # permissions-nodes-config-file-enabled=
    # permissions-accounts-config-file-enabled=
    # permissions-nodes-contract-enabled=
    # permissions-nodes-contract-address=

    # # Privacy
    # privacy-enabled=
    # privacy-url=
    # privacy-precompiled-address=
   
   
    ## METRICS
    #metrics-enabled=false
    #metrics-host="0.0.0.0"
    #metrics-port="9545"
    ## METRICS PUSH
    metrics-push-enabled=true
    metrics-push-host="pushgateway-svc"
    metrics-push-port="9091"
    metrics-push-interval="15"
    metrics-push-prometheus-job="besu"
