apiVersion: v1
kind: Service
metadata:
  name: pushgateway-svc
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: prometheus-pushgateway
  sessionAffinity: None
  type: ClusterIP
