apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
    name: besu-11-opg
    namespace: besu-11
spec:
  targetNamespaces:
    - besu-11
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generation: 1
  labels:
    operators.coreos.com/rhods-prometheus-operator.besu-11: ""
  name: rhods-prometheus-operator
  namespace: besu-11
spec:
  channel: beta
  installPlanApproval: Automatic
  name: rhods-prometheus-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: rhods-prometheus-operator.4.10.0
