- hosts: localhost

  tasks:
    - name: Auth in openshift
      kubernetes.core.k8s_auth:
        host: "{{ openshift_cluster }}"
        username: "{{ openshift_username }}"
        password: "{{ openshift_password }}"
        validate_certs: false

    - name: Create new project
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: project.openshift.io/v1
          kind: ProjectRequest
          metadata:
            name: "{{ project_name }}"
            labels:
              openshift.io/cluster-monitoring: 'true'
          displayName: "{{ project_display_name }}"
          description: "{{ project_description }}"
      ignore_errors: true

    - name: Create StorageClass
      kubernetes.core.k8s:
        src: ../yaml/aro/azurefile-csi-nfs.yml
        state: present

    - name: Create grafana pvc
      kubernetes.core.k8s:
        src: ../yaml/aro/grafana/01_grafana-instance-pvc.yml
        state: present
        namespace: "{{ project_name }}"

    - name: Deploy grafana operator
      kubernetes.core.k8s:
        src: ../yaml/aro/grafana/00_operator.yml
        state: present

    - name: Create grafana instances
      kubernetes.core.k8s:
        src: ../yaml/aro/grafana/02_instances.yml
        state: present
        namespace: "{{ project_name }}"

    - name: Create datasource
      kubernetes.core.k8s:
        src: ../yaml/aro/grafana/03_grafana_data_source.yml
        state: present
        namespace: "{{ project_name }}"

    - name: Create dashboard
      kubernetes.core.k8s:
        src: ../yaml/aro/grafana/04_grafana_dashboard.yml
        state: present
        namespace: "{{ project_name }}"

    - name: Create grafana route
      kubernetes.core.k8s:
        src: ../yaml/aro/grafana/05_route.yml
        state: present
        namespace: "{{ project_name }}"

    - name: Prepare operator
      ansible.builtin.template:
        src: ../yaml/aro/prometheus/00_operator.yml.j2
        dest: ../yaml/aro/prometheus/00_operator.yml

    - name: Deploy prometheus operator
      kubernetes.core.k8s:
        src: ../yaml/aro/prometheus/00_operator.yml
        state: present
        namespace: "{{ project_name }}"

    - name: Prepare subscription
      ansible.builtin.template:
        src: ../yaml/aro/prometheus/01_subscription.yml.j2
        dest: ../yaml/aro/prometheus/01_subscription.yml

    - name: Deploy subscription
      kubernetes.core.k8s:
        src: ../yaml/aro/prometheus/01_subscription.yml
        state: present
        namespace: "{{ project_name }}"

    - name: Create prometheus instances
      kubernetes.core.k8s:
        src: ../yaml/aro/prometheus/02_instances.yml
        state: present
        namespace: "{{ project_name }}"

    - name: Create prometheus route
      kubernetes.core.k8s:
        src: ../yaml/aro/prometheus/03_route.yml
        state: present
        namespace: "{{ project_name }}"

    - name: Create prometheus scrape config
      kubernetes.core.k8s:
        src: ../yaml/aro/prometheus/05_additional-scrape-configs.yml
        state: present
        namespace: "{{ project_name }}"
