---
- hosts: localhost
  tasks:
    - name: Autenticação no OpenShift
      k8s_auth:
        host: "https://YOUR_OPENSHIFT_CLUSTER"
        username: "YOUR_USERNAME"
        password: "YOUR_PASSWORD"
        validate_certs: no

    - name: Cria um novo projeto
      k8s:
        state: present
        definition:
          apiVersion: project.openshift.io/v1
          kind: ProjectRequest
          metadata:
            name: my-new-project
          displayName: "My New Project"
          description: "My new project description"

    - name: Deploy da aplicação
      k8s:
        state: present
        namespace: my-new-project
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: my-app
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: my-app
            template:
              metadata:
                labels:
                  app: my-app
              spec:
                containers:
                  - name: my-app-container
                    image: "YOUR_IMAGE_NAME:TAG"

    - name: Expondo o serviço
      k8s:
        state: present
        namespace: my-new-project
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: my-app-service
          spec:
            selector:
              app: my-app
            ports:
              - protocol: TCP
                port: 80
                targetPort: 8080

    - name: Criando uma rota para a aplicação
      k8s:
        state: present
        namespace: my-new-project
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: my-app-route
          spec:
            to:
              kind: Service
              name: my-app-service
              weight: 100
            port:
              targetPort: 8080