apiVersion: apps/v1
kind: Deployment
metadata:
  name: besu
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: besu
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: besu
    spec:
      containers:
      - image: ghcr.io/redhat-sa-brazil/drex-besu:sha256-169ed9d5754919fc158078262bf376b6c1a969ba975a1d4ced198d8bf7199c42
        imagePullPolicy: IfNotPresent
        name: container
        ports:
        - containerPort: 8545
          protocol: TCP
        - containerPort: 8546
          protocol: TCP
        - containerPort: 8547
          protocol: TCP
        - containerPort: 8550
          protocol: TCP
        - containerPort: 8551
          protocol: TCP
        - containerPort: 30303
          protocol: TCP
        - containerPort: 30303
          protocol: UDP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
