apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  creationTimestamp: "2023-09-08T20:00:47Z"
  generation: 3
  name: besu-pipeline
  namespace: pipeline
  resourceVersion: "159156"
  uid: 38306796-0e52-4ec6-88b9-494f0055d6c5
spec:
  tasks:
  - name: git-clone
    params:
    - name: url
      value: https://github.com/redhat-sa-brazil/drex-besu.git
    - name: revision
      value: main
    - name: refspec
      value: ""
    - name: submodules
      value: "true"
    - name: depth
      value: "1"
    - name: sslVerify
      value: "true"
    - name: crtFileName
      value: ca-bundle.crt
    - name: subdirectory
      value: ""
    - name: sparseCheckoutDirectories
      value: ""
    - name: deleteExisting
      value: "true"
    - name: httpProxy
      value: ""
    - name: httpsProxy
      value: ""
    - name: noProxy
      value: ""
    - name: verbose
      value: "true"
    - name: gitInitImage
      value: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:1a50511583fc02a27012d17d942e247813404104ddd282d7e26f99765174392c
    - name: userHome
      value: /home/git
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: pipeline-workspace
  - name: buildah
    params:
    - name: IMAGE
      value: image-registry.openshift-image-registry.svc:5000/pipeline/besu
    - name: BUILDER_IMAGE
      value: registry.redhat.io/rhel8/buildah@sha256:00795fafdab9bbaa22cd29d1faa1a01e604e4884a2c935c1bf8e3d1f0ad1c084
    - name: STORAGE_DRIVER
      value: vfs
    - name: DOCKERFILE
      value: ./Dockerfile
    - name: CONTEXT
      value: .
    - name: TLSVERIFY
      value: "true"
    - name: FORMAT
      value: oci
    - name: BUILD_EXTRA_ARGS
      value: ""
    - name: PUSH_EXTRA_ARGS
      value: ""
    - name: SKIP_PUSH
      value: "false"
    runAfter:
    - git-clone
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
    - name: source
      workspace: pipeline-workspace
  workspaces:
  - name: pipeline-workspace
